<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Resource;
use Faker\Generator as Faker;

$factory->define(Resource::class, function (Faker $faker) {
    return [
        'course_id' => $faker->randomElement([
            1, 2, 4, 3, 6, 7, 3, 5, 12, 2, 20, 21, 15, 16, 10, 11, 13, 17, 19
        ]),
        'author_id' => $faker->randomElement([
            1, 2, 4, 3, 6, 7,3, 5
        ]),
        'file' => $faker->randomElement([
            'resources/1.pdf',
            'resources/2.pdf',
            'resources/3.pdf',
            'resources/4.pdf',
            'resources/5.pdf',
            'resources/6.pdf',
            'resources/7.pdf',
            'resources/8.pdf',
            'resources/9.pdf',
            'resources/10.pdf',
            'resources/11.pdf',
        ]),
        'summary' => $faker->randomElement([
            'PDF, 23 page(s) 22 MB',
            'PDF, 6 page(s) 0.6 MB',
            'PDF, 3 page(s) 229 MB',
            'PDF, 2 page(s) 12 MB',
            'PDF, 1 page(s) 202 MB',
            'PDF, 8 page(s) 10 MB',
            'PDF, 9 page(s) 100 MB',
            'PDF, 5 page(s) 22 MB',
            'PDF, 1 page(s) 3 MB',
            'PDF, 7 page(s) 55 MB',
            'PDF, 66 page(s) 44 MB',
            'PDF, 77 page(s) 0.44 MB',
            'PDF, 5 page(s) 0.16 MB',
            'PDF, 1 page(s) 9 MB',
            'PDF, 4 page(s) 12 MB',
            'PDF, 7 page(s) 8 MB',
            'PDF, 2 page(s) 5 MB',
            'PDF, 4 page(s) 99 MB',
            'PDF, 11 page(s) 23 MB',
            'PDF, 4 page(s) 109 MB'
        ]),
        'title' => $faker->randomElement([
            'Basics of CCNP',
            'Basics of CCNA',
            'Basics of CCDP',
            'Basics of CCIE',
            'Introduction to networking',
            'Networking roadmap 2018',
            'Networking roadmap 2019',
            'Networking roadmap 2033',
            'Networking roadmap 2008',
            'Networking roadmap 2009',
            'Networking for bosses',
            'Networking, A deeper insight',
            'Networking, tips and tricks',
            'Networking with annie',
            'Networking with sam',
            'CCNP key points',
            'CCNA key points',
            'CCIE key points',
            'CCPD key points',
            'Professional CCNA',
            'Professional CCNP',
            'Professional CCIE',
            'Professional CCDP',
            'Professional networking in nigeria',
            'Modern steps in networking',
            'Learn to be efficient in networking',
            'Learn to master networking',
            'Learn to master networking and networking',
            'Networking, networking and networking',
            'Networking in 10 minutes',
            'Networking in 100 minutes',
            'Networking history',
            'CCNA history',
            'CCNP history',
            'CCIE history',
            'CCSP history',
            'CCDP history',
            'Networking masters',
            'Master networking like a boss',
            'Cover up in networking',
            'Cover up to networking',
            'be a CCNA guru',
            'be a CCNP guru',
            'be a CCIE guru',
            'be a CCDP guru',
            'be a CCSP guru',
            'networking essentials',
            'CCNA essentials',
            'CCDP essentials',
            'CCIE essentials',
            'CCNP essentials',
            'N+',
            'CCSP+',
        ]),
    ];
});